# Description:
#   - Release Nu Pkgs
# REF:
#   - https://github.com/marketplace/actions/checkout
#   - https://github.com/chawyehsu/moonbit-binaries/releases

name: Nu Pkgs
on:
  push:
    branches:
      - main
      - develop

    paths-ignore:
      - '**.md'

jobs:
  release-pkgs:
    runs-on: ubuntu-latest
    name: Build Nu Pkgs
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Nushell
        uses: hustcer/setup-nu@v3

      - name: Check Nushell Version
        shell: nu {0}
        run: |
          version
