# Description:
#   - Release Nu Pkgs
# REF:
#   - https://github.com/marketplace/actions/checkout
#   - https://github.com/chawyehsu/moonbit-binaries/releases

name: Nu Pkgs
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop

    paths-ignore:
      - '**.md'

jobs:
  release-pkgs:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, ubuntu-22.04-arm]
    runs-on: ${{ matrix.os }}
    name: Build Nu Pkgs@${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Nushell
        uses: hustcer/setup-nu@v3

      - name: Check Nushell Version
        shell: nu {0}
        run: |
          version

      - name: Install nfpm
        run: |
          echo 'deb [trusted=yes] https://repo.goreleaser.com/apt/ /' | sudo tee /etc/apt/sources.list.d/goreleaser.list
          sudo apt update
          sudo apt install nfpm
          nfpm --version

