# Description:
#   - Release Nu Pkgs
# REF:
#   - https://github.com/marketplace/actions/checkout
#   - https://github.com/chawyehsu/moonbit-binaries/releases

name: Test Install Nu Pkgs
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop

    paths-ignore:
      - '**.md'

jobs:
  install-pkgs:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, ubuntu-22.04-arm, ubuntu-24.04, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    name: Install Nu Pkgs@${{ matrix.os }}
    steps:
      - name: Test Install Nushell from Gemfury
        run: |
          curl -fsSL https://apt.fury.io/nushell/gpg.key | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/fury-nushell.gpg
          echo "deb https://apt.fury.io/nushell/ /" | sudo tee /etc/apt/sources.list.d/fury.list
          sudo apt update
          sudo apt install nushell
          which nu
          nu -c 'version'
