# Description:
#   - Release Nu Pkgs
# REF:
#   - https://github.com/marketplace/actions/checkout
#   - https://gemfury.com/guide/alpine/configure-apk/

name: Test Install Nu Pkgs
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop

    paths-ignore:
      - '**.md'

jobs:
  install-apk:
    name: Install Nu apk
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    container:
      image: alpine:latest
    steps:
      - name: Install Nushell APK
        run: |
          # Append Gemfury Nushell apk repository
          echo "https://alpine.fury.io/nushell/" | tee -a /etc/apk/repositories
          apk update
          # Use --allow-untrusted since the apk package is not signed currently
          apk add --allow-untrusted nushell
          which nu
          nu -c 'version'

  install-rpm:
    name: Install Nu rpm on RHC
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm]
        image:
          - registry.access.redhat.com/ubi8/ubi:latest
          - registry.access.redhat.com/ubi9/ubi:latest
    runs-on: ${{ matrix.os }}
    container:
      image: ${{ matrix.image }}
    steps:
      - name: Test Install Nushell
        run: |
          # Create repo config file pointing to Gemfury
          echo "[gemfury-nushell]
          name=Gemfury Nushell Repo
          baseurl=https://yum.fury.io/nushell/
          enabled=1
          gpgcheck=0
          gpgkey=https://yum.fury.io/nushell/gpg.key" | tee /etc/yum.repos.d/fury-nushell.repo
          # Install Nushell via dnf
          dnf install -y nushell
          # Print nushell executable and version to verify installation
          which nu
          nu -c 'version'

  install-deb:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, ubuntu-22.04-arm, ubuntu-24.04, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    name: Install Nu deb@${{ matrix.os }}
    steps:
      - name: Test Install Nushell from Gemfury
        run: |
          curl -fsSL https://apt.fury.io/nushell/gpg.key | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/fury-nushell.gpg
          echo "deb https://apt.fury.io/nushell/ /" | sudo tee /etc/apt/sources.list.d/fury.list
          sudo apt update
          sudo apt install nushell
          which nu
          nu -c 'version'
